### ISSUE TITLE
Add physical requirements that can be specified in Jobs

### ISSUE THREAD

**Issue by SethMichaelLarson** [beanstalk-ci/beanstalk#241]
```yaml
jobs:
  - install:
      git clone https://github.com/rust-lang/rust
      cd rust
      python ./x.py build
      sudo python ./x.py install
    sudo: true
    memory: 2GB  # <---- This is what I'm talking about.
    disk: 1GB
```

Defaults: memory=64MB disk=64MB
